server:
  port: 17681

spring:
  application:
    name: socketKeyAPI
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    show-sql: true
    defer-datasource-initialization: true

keepAlive:
  default:
    timeout: 900

fileReader:
  jsonDirectory: D:\\sandbox\\DTM_2024_09_11\\0911_203\\original
